bookers2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'homes/about' => 'homes#about', as: "about"
  resources :users, only: [:new, :index, :show, :edit, :update, :create]
  resources :books, only: [:new, :index, :show, :edit, :update, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

bookers2/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true
end

bookers2/app/models/post_image.rb
class PostImage < ApplicationRecord
  
  has_one_attached : image
  
end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books, dependent: :destroy


has_one_attached :profile_image
validates :name, presence: true


def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
end




end

bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_perameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
  
  protected
  
  def configure_permitted_perameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController
   
  def new
    @book = Book.new
  end
  
  def create 
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
     redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end
  
  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end
  
  def show
    @book = Book.new
    @bookfind = Book.find(params[:id])
    @user = @bookfind.user
  end
  
  def edit
    @bookfind = Book.find(params[:id])
  end
  
  def update
    @bookfind = Book.find(params[:id])
    if @bookfind.update(book_params)
     redirect_to book_path(@bookfind.id), notice: "You have updated book successfully."
    else
      render :edit
    end
  end
  
  def destroy
    @bookfind = Book.find(params[:id])
    @bookfind.destroy
    redirect_to books_path
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
 
end

bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = current_user
    if @user.update(user_params)
     redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
     render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/books/_info.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
   <h2>User info</h2>
   
   <%= image_tag user.get_profile_image(100, 100) %>
   
   <table class="table">
    <tbody>
     <tr></tr>
     <tr>
      <th>name</th>
      <th><%= user.name %></th>
     </tr>
     <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
     </tr>
    </tbody>
   </table>
   
   <div class="row">
    <svg class="svg-inline--fa fa-user-cog fa-w-20" aria-hidden="true" focusable="false"
    data-prefix="fas" data-icon="user-cog" role="img" xmlus="http://www.w3.org/2000/svg"
    viewBox="0 0 640 512" data-fa-i2svg></svg>
    <%= link_to icon('fas','user-cog'), edit_user_path(user.id), class: 'btn btn-outline-secondary btn-block edit_user_id' %>
   </div>
   
   <h2 class="mt-3">Now book</h2>
    <%= form_with model:book do |f| %>
    <div class="form-group">
     <label for="book_title">Title</label>
     <%= f.text_field :title, class: 'form-control book_title' %>
    </div>
    <div class="form-group">
     <label for="book_opinion">Opinion</label>
     <%= f.text_area :body, class: 'form-control book_body' %>
    </div>
    <div class="form-group">
     <%= f.submit 'Create Book', class: 'btn btn-success' %>
    </div>
    <% end %>
  </div>

bookers2/app/views/books/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h1>Editing Book</h1>
    
     <% if @bookfind.errors.any? %>
      <h3><%= @bookfind.errors.count %>error prohibited this obj from being saved:</h3>
       <ul>
        <%= @bookfind.errors.full_messages.each do |message| %>
         <li><%= message %></li>
        <% end %>
       </ul>
     <% end %>
    
    <%= form_with model:@bookfind do |f| %>
     <div class="form-group">
       <label for="book_title">Title</label>
       <%= f.text_field :title, id:"book_title", class: 'form-control book_title'%>
     </div>
    
     <div class="form-group">
       <label for="book_body">Opinions</label>
       <%= f.text_area :body, id:"book_body", class: 'form-control book_body'%>
     </div>
    
     <div class="form-group">
       <%= f.submit "Update Book", class: 'btn btn-success'%>
     </div>
    <% end %>
    
    <%= link_to "Show", book_path(@bookfind.id) %>
    <%= " | " %>
    <%= link_to "Back", books_path %>
  </div>
 </div>
</div>

bookers2/app/views/books/index.html.erb
 <%= render 'info', user:@user, book:@book %>
  
  <% if @book.errors.any? %>
   <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
   <ul>
    <%= @book.errors.full_messages.each do |message| %>
     <li><%= message %></li>
    <% end %>
   </ul>
  <% end %>
  
  
  <div class="col-md-8 offset-md-1">
   <h2>Books</h2>
   <table class="table table-hover table-inverse">
    <thead>
     <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
     </tr>
    </thead>
     <% @books.each do |book| %>
   <tbody>
    <tr>
     <td><%= image_tag @user.get_profile_image(100, 100) %></td>
     <td><%= link_to book.title,  book_path(book.id), class: 'book_id'%></td>
     <td><%= book.body %></td>
    </tr>
   </tbody>
  <% end %>
   </table>
  </div>
 </div>
</div>
 
 
 




 

bookers2/app/views/books/new.html.erb
<h1>Books#new</h1>

<p>Find me in app/views/books/new.html.erb</p>

bookers2/app/views/books/show.html.erb
<%= render 'info', user:@user, book:@book %>

<div class="col-md-8 offset-md-1">
 <h2>Book detail</h2>

 <table class="table">
  <tbody>
   <tr>
    <td><%= link_to user_path(@bookfind.user.id) do %>
        <%= image_tag(@bookfind.user.get_profile_image(100, 100)) %>
        <br><%= @user.name %>
        <% end %></td>
    <td><%= link_to @bookfind.title, book_path(@bookfind.id) %></td>
    <td><%= @bookfind.body %></td>
    <td>
     <% if @bookfind.user == current_user %>
      <%= link_to "Edit", edit_book_path(@bookfind.id), class: 'btn btn-sm btn-success edit_book_id' %>
     <% end %>
     </td>
    <td>
     <% if @bookfind.user == current_user %>
      <%= link_to "Destroy", book_path(@bookfind.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: 'btn btn-sm btn-danger destroy_book_id' %>
     <% end %>
     </td>
   </tr>
  </tbody>
 </table>
</div>

bookers2/app/views/users/edit.html.erb
<p id='notice'></p>
<div class="container">
 <div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    
     <% if @user.errors.any? %>
      <h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
       <ul>
        <%= @user.errors.full_messages.each do |message| %>
         <li><%= message %></li>
        <% end %>
       </ul>
     <% end %>
    
    <%= form_with model:@user do |f| %>
    
    <div class="form-group">
      <label for="user_name">Name</label>
      <%= f.text_field :name, id:"user_name", class: 'form-control name'%>
    </div>
    
    <div class="form-group">
       <label for="user_Image">Image</label>
       <%= f.file_field :profile_image, id:"user_profile_image", accept: "image/*", class: 'form-control-file user_image'%>
    </div>
    
    <div class="form-group">
      <label for="user_introduction">Introduction</label>
      <%= f.text_area :introduction, id:"user_introduction", class: 'form-control introduction'%>
    </div>
    
    <div class="form-group">
      <%= f.submit "Update User", class: 'btn btn-secondary'%>
    </div>
    <% end %>
  </div>
 </div>
</div>

  

bookers2/app/views/users/index.html.erb
<%= render 'books/info', user:@user, book:@book %>


<div class="col-md-8 offset-md-1">
   <h2>Users</h2>
   <table class="table table-hover table-inverse">
    <thead>
     <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
     </tr>
    </thead>
     <% @users.each do |user| %>
    <tbody>
     <tr>
      <td><%= image_tag user.get_profile_image(100, 100) %></td>
      <td><%= user.name %></td>
      <td><%= link_to "show",  user_path(user.id), class: 'book_id'%></td>
     </tr>
    </tbody>
  <% end %>
   </table>
  </div>
 </div>
</div>
 

bookers2/app/views/users/show.html.erb
<%= render 'books/info', user:@user, book:@book %>

<div class="col-md-8 offset-md-1">
   <h2>Books</h2>
   <table class="table table-hover table-inverse">
    <thead>
     <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
     </tr>
    </thead>
   <tbody>
    <% @books.each do |book| %>
    <tr>
     <td><%= image_tag book.user.get_profile_image(100, 100) %>
     </td>
     <td><%= link_to book.title, book_path(book.id)%></td>
     <td><%= book.body %></td>
    </tr>
    <% end %>
   </tbody>
   </table>
  </div>
 </div>
</div>