bookers/config/routes.rb
Rails.application.routes.draw do
  root :to=>'homes#top'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

bookers/app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end

  def index
    @books = Book.new
    @lists = Book.all
  end

  def create
    @books = Book.new(book_params)
    if @books.save
      redirect_to book_path(@books.id), notice: "Book was successfully created."
    else
      @lists = Book.all
      render :index
    end
  end


  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     redirect_to book_path(@book.id), notice: "Book was successfully updated."
    else
      render :show
    end
  end

  def destroy
   book = Book.find(params[:id])
   book.destroy
   redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

bookers/app/views/books/edit.html.erb
<h1 class="view-title">Editing Book</h1>

<% if @book.errors.any? %>
 <%= @book.errors.count %>error prohibited this book from being saved:
 <ul>
  <% @book.errors.full_messages.each do |message|%>
   <li><%= message %></li>
  <% end %>
 </ul>
<% end %>


<%= form_with model: @book, url: update_book_path(@book.id), mehod: :patch do |f|%>

<div class="field">
 <p>Title</p>
 <%= f.text_field :title %> 
</div>

<div class="field"> 
 <p>Body</p>
 <%= f.text_area :body %> 
</div>

<div class="actions">
 <%= f.submit 'Update Book'%>
</div>
 
 
 <%= link_to "show", book_path(@book.id)%>
 <%= link_to "Back", books_path %>
 
 <% end %>

bookers/app/views/books/index.html.erb
<h1 class="view-title">Books</h1>

<div class="books-box">
 <table>
   <thead>
    <tr>
     <th>Title</th>
     <th>Body</th>
     <th colspan="3"></th>
    </tr>
   </thead>
   
   <% @lists.each do |book| %>
   <tbody>
    <tr>
     <td><%= book.title %></td>
     <td><%= book.body %></td>
     <td><%= link_to "show", book_path(book.id)%></td>
     <td><%= link_to "Edit", edit_book_path(book.id)%></td>
     <td><%= link_to "Destroy", book_path(book.id), method: :delete, "date-confirm" => "本当に削除しますか？"%></td>
    </tr>
   </tbody>
  <% end %>
 </table>
</div>


<h2 class="view-title">New books</h2>

<% if @books.errors.any? %>
 <%= @books.errors.count %>error prohibited this book from being saved:
 <ul>
  <% @books.errors.full_messages.each do |message|%>
   <li><%= message %></li>
  <% end %>
 </ul>
<% end %>

<%= form_with model: @books, url: '/books', method: :post do |f| %>

<div class="field">
 <p>Title</p>
 <%= f.text_field :title %>
</div>
 
<div class="field">
 <p>Body</p>
 <%= f.text_area :body %>
</div>
 
 <%= f.submit 'Create Book'%>
<% end %>

bookers/app/views/books/new.html.erb
<h2>New books</h2>

<%= form_with model: Book.new do |f| %>
 <% f.text_field :title %>
<% end %>

bookers/app/views/books/show.html.erb
<% if @book.errors.any? %>
 <%= @book.errors.count %>error prohibited this book from being saved:
 <ul>
  <% @book.errors.full_messages.each do |message|%>
   <li><%= message %></li>
  <% end %>
 </ul>
<% end %>


<p class="top-text"><strong>Title:</strong><%= @book.title %></p>
<p class="top-text"><strong>Body:</strong><%= @book.body %></p>


<%= link_to "Edit", edit_book_path(@book.id)%>
<%= link_to "Back", books_path %>

bookers/app/views/books/top.html.erb
<h1>Books#top</h1>
<p>Find me in app/views/books/top.html.erb</p>

bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>

  <body>
    <div class="text-success">
      <%= flash[:notice] %>　
    </div>
      <%= yield %>
  </body>
</html>